import MainTemplate from "@/components/MainTemplate"

export const metadata = {
   title: 'Dashboard | Digital Library',
   description: 'Generated by create next app',
}


type PropsLayout = {
   children: React.ReactNode
}


const RootLayout = ({ children }: PropsLayout) => {
   return (
       <MainTemplate>
        {children}
       </MainTemplate>
   )
}


export default RootLayout